# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc0521546610d96ca096df7595f38f2cfd289d92637bacd65142c7ee5c6cd6f55b89f8bbcd01cf01036e6a33c57b56a2c34b28d1cc62e1606be89708b7d580dd

test:
  secret_key_base: 5ac303fcc7a9a75f2a9ce7b5c2f89d5ef67dd13cf9c88bf982b8399d666a06e9ce917f6b27f2aa142220212a0b6385ab65d47cb4a06a5aa03f1ee1fd98b05d6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
