# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b5a5f4de3d6259bd653e71f450704131812c597eace4200ff8f1cc91434400fb2d0c8fc0016517a594aa67ccbb3819ca53743e773bc33dc11c395f7f3dbc133

test:
  secret_key_base: 94d1103b2d87b5240dd2283733de9ff36334ad5a3ee1960be539098dcaa4d481f8c5fc22cf80996efb5e4f81d570a278d9225a02110cb9519e0e64dd66f2bd40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
