# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c71467904a505afea341e9bbfffdaeec5f2e98ffa5d8ac3afad119a50836d8e7856f8f6e8fbcc543baa65bd48f3592841aa78999915066cfff2d1514bb04450

test:
  secret_key_base: dffb83d147d960dc284db37582e15077d7cb18ad87b498e9ab030a65b5da0d4f094e2c8c1f69afefc8deea739c735fa0e47d9bc442c33a72983669a6ee349808

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
