# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3768bd1dd13b672149501d4c3827adcb8aed1e1891a0fdc7375f9f9274681cb688841e2a527e12a0169e7ce98443d06ab501d2c3fefacfad1b0bf9c6f9dc16c0

test:
  secret_key_base: 43014ed296e019346d30deda94317a8772189f87a94ae4a8ec276146e58818d3c5fd828ba0bc4ec705b07fdd22300bc5063d7aeb58fdca2de9407ba604ce4a6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
